export const BUSINESS_LOCATION = [
  "em Ribeirão Preto",
  "em Ribeirão Preto SP",
  "em Ribeirão Preto, SP",
  "para Ribeirão Preto",
  "para Ribeirão Preto SP",
  "com atendimento em Ribeirão Preto",
  "com atendimento em Ribeirão Preto SP",
  "com entrega em Ribeirão Preto",
  "com entrega em Ribeirão Preto SP",
  "com opções para Ribeirão Preto",
  "com opções para Ribeirão Preto SP",
  "com disponibilidade em Ribeirão Preto",
  "com disponibilidade em Ribeirão Preto SP",
  "em toda a região de Ribeirão Preto",
  "na cidade de Ribeirão Preto",
  "na cidade de Ribeirão Preto SP",
  "no mercado de Ribeirão Preto",
  "no mercado de Ribeirão Preto SP",
  "para clientes de Ribeirão Preto",
  "para clientes de Ribeirão Preto SP",
  "com foco em Ribeirão Preto",
  "com foco em Ribeirão Preto SP",
  "voltado a Ribeirão Preto",
  "voltado a Ribeirão Preto SP",
  "com presença em Ribeirão Preto",
  "com presença em Ribeirão Preto SP",
  "com atuação em Ribeirão Preto",
  "com atuação em Ribeirão Preto SP",
  "perto de você em Ribeirão Preto",
  "perto de você em Ribeirão Preto SP",
  "na região de Ribeirão Preto",
  "na região de Ribeirão Preto SP",
  "para quem compra em Ribeirão Preto",
  "para quem compra em Ribeirão Preto SP",
  "com soluções em Ribeirão Preto",
  "com soluções em Ribeirão Preto SP",
  "no polo de Ribeirão Preto",
  "no polo de Ribeirão Preto SP",
  "na área de Ribeirão Preto",
  "na área de Ribeirão Preto SP",
  "com cobertura em Ribeirão Preto",
  "com cobertura em Ribeirão Preto SP",
  "com alcance em Ribeirão Preto",
  "com alcance em Ribeirão Preto SP",
  "para a região de Ribeirão Preto",
  "para a região de Ribeirão Preto SP",
  "em Ribeirão Preto e região",
  "em Ribeirão Preto SP e região",
  "para o público de Ribeirão Preto",
  "para o público de Ribeirão Preto SP",
  "com operação em Ribeirão Preto",
  "com operação em Ribeirão Preto SP",
  "com ofertas em Ribeirão Preto",
  "com ofertas em Ribeirão Preto SP",
  "para compras em Ribeirão Preto",
  "para compras em Ribeirão Preto SP",
  "com suporte em Ribeirão Preto",
  "com suporte em Ribeirão Preto SP",
  "para atender Ribeirão Preto",
  "para atender Ribeirão Preto SP",
  "em Ribeirão Preto, interior de São Paulo",
  "no interior de São Paulo, em Ribeirão Preto",
  "com atendimento local em Ribeirão Preto",
  "com atendimento local em Ribeirão Preto SP",
  "com entrega local em Ribeirão Preto",
  "com entrega local em Ribeirão Preto SP",
  "para a cidade de Ribeirão Preto",
  "para a cidade de Ribeirão Preto SP",
  "com soluções locais em Ribeirão Preto",
  "com soluções locais em Ribeirão Preto SP",
  "com opções disponíveis em Ribeirão Preto",
  "com opções disponíveis em Ribeirão Preto SP",
  "no cenário local de Ribeirão Preto",
  "no cenário local de Ribeirão Preto SP",
  "com presença local em Ribeirão Preto",
  "com presença local em Ribeirão Preto SP",
  "voltado ao mercado de Ribeirão Preto",
  "voltado ao mercado de Ribeirão Preto SP",
  "com atendimento para a região de Ribeirão Preto",
  "com atendimento para a região de Ribeirão Preto SP",
  "com entrega para a região de Ribeirão Preto",
  "com entrega para a região de Ribeirão Preto SP",
  "com soluções para clientes de Ribeirão Preto",
  "com soluções para clientes de Ribeirão Preto SP",
  "com facilidade de compra em Ribeirão Preto",
  "com facilidade de compra em Ribeirão Preto SP",
  "com opções pensadas para Ribeirão Preto",
  "com opções pensadas para Ribeirão Preto SP",
  "com variedade para Ribeirão Preto",
  "com variedade para Ribeirão Preto SP",
  "com seleção para Ribeirão Preto",
  "com seleção para Ribeirão Preto SP",
  "com conveniência em Ribeirão Preto",
  "com conveniência em Ribeirão Preto SP",
  "com atendimento próximo em Ribeirão Preto",
  "com atendimento próximo em Ribeirão Preto SP",
  "com soluções para o dia a dia em Ribeirão Preto",
  "com soluções para o dia a dia em Ribeirão Preto SP",
  "para consumidores de Ribeirão Preto",
  "para consumidores de Ribeirão Preto SP",
] as const;
