export const PRODUCT_BENEFIT_TERMS = [
  "com mais praticidade no dia a dia",
  "com melhor aproveitamento no uso diário",
  "com soluções que facilitam a rotina",
  "com mais eficiência para a aplicação certa",
  "com bom custo-benefício para sua compra",
  "com recursos que agregam valor ao uso",
  "com mais conveniência para quem precisa de agilidade",
  "com desempenho pensado para necessidades reais",
  "com alternativas que ajudam a ganhar tempo",
  "com opções que favorecem uma compra mais inteligente",
  "com mais funcionalidade para diferentes cenários",
  "com praticidade para resolver o que você precisa",
  "com benefícios pensados para o uso contínuo",
  "com utilidade para demandas do dia a dia",
  "com mais segurança na escolha do item certo",
  "com diferenciais que ajudam no resultado final",
  "com mais comodidade para equipar sua rotina",
  "com qualidade para investir melhor",
  "com opções que melhoram a experiência de uso",
  "com soluções que unem praticidade e desempenho",
  "com versatilidade para diferentes necessidades",
  "com mais confiança para escolher sem complicação",
  "com benefícios que valorizam o investimento",
  "com mais produtividade para seu projeto",
  "com vantagens para quem busca eficiência real",
] as const;

export const PRODUCT_PROOF_TERMS = [
  "com detalhes que ajudam a comparar modelo, aplicação e acabamento",
  "com informações úteis para avaliar a escolha com mais clareza",
  "com recursos que tornam a comparação mais simples",
  "com argumentos práticos para entender os diferenciais",
  "com variedade para analisar versões e possibilidades",
  "com contexto para identificar o melhor encaixe",
  "com pontos de comparação que apoiam uma decisão mais precisa",
  "com critérios para avaliar uso, desempenho e proposta",
  "com referências para comparar preço e benefício",
  "com elementos que ajudam a perceber o diferencial",
  "com dados que favorecem uma escolha mais assertiva",
  "com informações relevantes para uma compra consciente",
  "com aspectos úteis para analisar cada opção",
  "com mais clareza para comparar alternativas similares",
  "com detalhes importantes para decidir com confiança",
  "com pontos de análise para escolher o modelo adequado",
  "com informações que ajudam a reduzir a dúvida na compra",
  "com critérios que facilitam a comparação entre versões",
  "com mais objetividade para avaliar o que faz sentido",
  "com sinais claros do que muda entre as opções",
  "com referências que apoiam a escolha pelo uso real",
  "com mais repertório para comparar antes de comprar",
  "com variedade para enxergar boas combinações",
  "com recursos para encontrar a opção mais aderente",
  "com informações que ajudam a escolher com mais segurança",
] as const;

export const PRODUCT_URGENCY_TERMS = [
  "aproveite para escolher a opção que melhor atende sua necessidade",
  "avance na compra com mais confiança",
  "aproveite para comparar e decidir sem perder tempo",
  "garanta uma escolha mais segura para seu uso",
  "aproveite para investir melhor na solução certa",
  "siga para a compra com mais clareza",
  "aproveite para encontrar a melhor opção para sua rotina",
  "faça uma escolha mais assertiva agora",
  "aproveite para comprar com mais critério",
  "dê o próximo passo com mais segurança na decisão",
  "aproveite para selecionar o item ideal para sua demanda",
  "compre com mais tranquilidade depois de comparar melhor",
  "aproveite para avançar com a opção mais adequada",
  "leve mais confiança para a etapa final da compra",
  "aproveite para decidir com mais objetividade",
  "escolha agora a alternativa que faz mais sentido",
  "aproveite para garantir mais aderência ao que você precisa",
  "avance com mais convicção na escolha do produto",
  "aproveite para resolver sua necessidade com mais eficiência",
  "faça a compra com mais clareza e segurança",
  "aproveite para encontrar a solução certa hoje",
  "siga com a escolha que entrega mais valor ao uso",
  "aproveite para comprar melhor e com menos dúvida",
  "defina agora a opção mais adequada para o seu contexto",
  "avance para a compra com a decisão mais bem embasada",
] as const;

export const CATEGORY_BENEFIT_TERMS = [
  "com mais clareza para explorar a categoria",
  "com variedade para ampliar sua análise",
  "com mais contexto para organizar a busca",
  "com opções para comparar diferentes caminhos",
  "com alternativas para pesquisar por necessidade",
  "com repertório para avaliar aplicações e estilos",
  "com mais praticidade para navegar pelas opções",
  "com seleção pensada para facilitar a descoberta",
  "com soluções para entender melhor o que a categoria oferece",
  "com variedade para encontrar possibilidades alinhadas ao seu objetivo",
  "com mais segurança para explorar linhas relacionadas",
  "com opções para refinar sua busca com tranquilidade",
  "com caminhos para ampliar sua visão da categoria",
  "com mais objetividade para analisar alternativas",
  "com diversidade para comparar cenários de uso",
  "com uma visão mais completa das opções disponíveis",
  "com mais praticidade para pesquisar antes de decidir",
  "com alternativas que ajudam a encontrar o melhor encaixe",
  "com mais repertório para entender a categoria",
  "com variedade para descobrir soluções complementares",
  "com critérios para navegar com mais confiança",
  "com opções que ajudam a organizar melhor a comparação",
  "com mais conveniência para explorar escolhas relevantes",
  "com possibilidades para aprofundar sua análise",
  "com mais clareza para descobrir o que vale a pena comparar",
] as const;

export const CATEGORY_PROOF_TERMS = [
  "com informações para comparar marcas, linhas e propostas",
  "com referências que ajudam a perceber diferenças importantes",
  "com critérios para analisar função, estilo e aplicação",
  "com pontos de comparação para entender o que muda entre as opções",
  "com elementos úteis para avaliar a categoria com mais precisão",
  "com contexto para comparar soluções relacionadas",
  "com detalhes que apoiam uma navegação mais inteligente",
  "com informações que ajudam a identificar o melhor caminho",
  "com sinais claros para avaliar alternativas com calma",
  "com recursos para comparar benefícios e usos",
  "com referências para analisar a categoria sem perder contexto",
  "com pontos de apoio para descobrir diferenças entre linhas",
  "com dados que favorecem uma comparação mais objetiva",
  "com informações para entender melhor cada proposta",
  "com aspectos relevantes para pesquisar com profundidade",
  "com referências que ampliam a leitura da categoria",
  "com elementos que tornam a comparação mais simples",
  "com detalhes que ajudam a visualizar novas possibilidades",
  "com critérios para comparar opções por finalidade e benefício",
  "com mais contexto para avaliar a aderência de cada alternativa",
  "com informações que ajudam a refinar a busca",
  "com referências para comparar soluções por cenário de uso",
  "com aspectos que apoiam uma análise mais segura",
  "com dados úteis para perceber o diferencial de cada linha",
  "com informações que deixam a comparação mais clara",
] as const;

export const CATEGORY_URGENCY_TERMS = [
  "explore as opções que mais combinam com sua busca",
  "avance na comparação com mais clareza",
  "descubra agora as alternativas mais aderentes ao seu objetivo",
  "siga na navegação com mais confiança",
  "refine sua escolha a partir das opções mais relevantes",
  "aprofunde a análise antes de decidir o próximo passo",
  "descubra quais caminhos fazem mais sentido para você",
  "avance na pesquisa com critérios mais claros",
  "explore combinações que podem ampliar sua decisão",
  "organize sua escolha com mais segurança",
  "veja agora as alternativas que merecem sua atenção",
  "siga para a próxima etapa com uma visão mais completa",
  "aproxime sua decisão da opção mais adequada",
  "avance na busca com mais objetividade",
  "descubra soluções que podem atender melhor seu contexto",
  "continue a comparação com mais repertório",
  "explore os caminhos mais relevantes para sua necessidade",
  "avance com mais convicção na análise da categoria",
  "descubra opções que ampliam suas possibilidades de escolha",
  "siga com uma leitura mais estratégica da categoria",
  "explore agora as seleções com maior aderência ao seu perfil",
  "avance na pesquisa com menos ruído e mais contexto",
  "identifique as opções que melhor se encaixam no que você procura",
  "descubra novas possibilidades antes de fechar sua decisão",
  "siga para as melhores alternativas com mais clareza",
] as const;
