export const PRODUCT_CALL_TO_ACTION = [
  "Confira opções de",
  "Veja ofertas de",
  "Encontre ofertas de",
  "Compare modelos de",
  "Descubra vantagens de",
  "Escolha a melhor opção de",
  "Veja condições para",
  "Aproveite oportunidades em",
  "Conheça soluções em",
  "Explore novidades em",
  "Confira alternativas de",
  "Veja seleções de",
  "Encontre a versão ideal de",
  "Descubra opções para",
  "Avalie benefícios de",
  "Confira detalhes de",
  "Veja lançamentos de",
  "Encontre modelos de",
  "Compare vantagens de",
  "Conheça mais sobre",
  "Veja escolhas para",
  "Confira recomendações de",
  "Encontre soluções para",
  "Veja recursos de",
  "Descubra diferenciais de",
  "Confira preços e opções de",
  "Veja variedades de",
  "Encontre alternativas para",
  "Conheça opções de compra para",
  "Compare versões de",
  "Confira condições especiais para",
  "Veja possibilidades com",
  "Encontre qualidade em",
  "Descubra utilidades de",
  "Conheça aplicações de",
  "Veja oportunidades para",
  "Confira benefícios de",
  "Encontre itens de",
  "Explore opções para",
  "Veja combinações com",
  "Confira modelos e versões de",
  "Encontre a escolha certa em",
  "Descubra soluções práticas com",
  "Veja opções confiáveis de",
  "Compare alternativas para",
  "Confira novidades para",
  "Encontre mais variedade em",
  "Veja o que muda com",
  "Descubra como usar",
  "Conheça linhas de",
  "Confira opções pensadas para",
  "Veja alternativas com",
  "Encontre o modelo certo de",
  "Descubra oportunidades para comprar",
  "Conheça os diferenciais de",
  "Confira a seleção de",
  "Veja soluções que facilitam",
  "Encontre praticidade com",
  "Compare faixas e opções de",
  "Confira escolhas inteligentes em",
  "Veja itens ideais para",
  "Encontre mais desempenho com",
  "Descubra boas escolhas em",
  "Conheça opções que entregam mais em",
  "Confira possibilidades para usar",
  "Veja alternativas que valem a pena em",
  "Encontre versões para o dia a dia de",
  "Descubra recursos presentes em",
  "Conheça opções sob medida para",
  "Confira soluções versáteis em",
  "Veja oportunidades de compra em",
  "Encontre mais eficiência com",
  "Descubra combinações para",
  "Conheça alternativas modernas de",
  "Confira linhas completas de",
  "Veja motivos para escolher",
  "Encontre desempenho e qualidade em",
  "Descubra opções com ótimo custo-benefício em",
  "Conheça possibilidades para renovar com",
  "Confira uma curadoria de",
  "Veja produtos e opções em",
  "Encontre o que você procura em",
  "Descubra o potencial de",
  "Conheça seleções para comparar",
  "Confira soluções com mais segurança em",
  "Veja opções para equipar com",
  "Encontre mais conforto com",
  "Descubra linhas para complementar",
  "Conheça alternativas para melhorar com",
  "Confira opções para quem busca",
  "Veja escolhas com entrega de valor em",
  "Encontre novas possibilidades com",
  "Descubra itens para facilitar o uso de",
  "Conheça opções para comprar com confiança em",
  "Confira alternativas para diferentes necessidades em",
  "Veja modelos desenvolvidos para",
  "Encontre soluções que ajudam no uso de",
  "Descubra opções para comparar antes de escolher",
  "Conheça versões que se destacam em",
  "Confira escolhas para comprar melhor",
] as const;

export const CATEGORY_CALL_TO_ACTION = [
  "Explore opções de",
  "Compare linhas de",
  "Veja variedades de",
  "Descubra alternativas em",
  "Conheça a seleção de",
  "Navegue por opções de",
  "Compare categorias de",
  "Veja soluções em",
  "Descubra itens de",
  "Conheça possibilidades em",
  "Explore a categoria de",
  "Compare estilos de",
  "Veja diferentes opções de",
  "Descubra modelos em",
  "Conheça linhas completas de",
  "Explore alternativas para",
  "Compare versões em",
  "Veja combinações de",
  "Descubra o universo de",
  "Conheça coleções de",
  "Explore escolhas em",
  "Compare ofertas de",
  "Veja seleções em",
  "Descubra tendências em",
  "Conheça famílias de",
  "Explore produtos de",
  "Compare recursos em",
  "Veja aplicações de",
  "Descubra opções para seu projeto em",
  "Conheça soluções para",
  "Explore novidades de",
  "Compare padrões de",
  "Veja oportunidades em",
  "Descubra a variedade de",
  "Conheça a linha de",
  "Explore soluções para sua rotina em",
  "Compare opções para diferentes usos em",
  "Veja o que há em",
  "Descubra escolhas para",
  "Conheça alternativas para comparar em",
  "Explore as possibilidades de",
  "Compare a seleção de",
  "Veja caminhos para escolher em",
  "Descubra itens para cada necessidade em",
  "Conheça opções que se destacam em",
  "Explore diferentes linhas de",
  "Compare possibilidades para",
  "Veja soluções para ambientes com",
  "Descubra opções para renovar em",
  "Conheça variedades de",
  "Explore combinações para",
  "Compare propostas em",
  "Veja linhas pensadas para",
  "Descubra opções para equipar com",
  "Conheça segmentos de",
  "Explore a curadoria de",
  "Compare alternativas em",
  "Veja opções para começar com",
  "Descubra linhas para complementar",
  "Conheça caminhos de compra em",
  "Explore ideias em",
  "Compare escolhas por necessidade em",
  "Veja opções para cada etapa de",
  "Descubra seleções de",
  "Conheça opções para pesquisar em",
  "Explore categorias para",
  "Compare tipos de",
  "Veja possibilidades para montar",
  "Descubra soluções pensadas para",
  "Conheça referências em",
  "Explore a diversidade de",
  "Compare opções com mais contexto em",
  "Veja alternativas para atualizar",
  "Descubra escolhas mais adequadas em",
  "Conheça categorias para comparar",
  "Explore opções para diferentes perfis em",
  "Compare linhas para uso em",
  "Veja soluções para organizar",
  "Descubra a seleção ideal de",
  "Conheça oportunidades de navegação em",
  "Explore opções com variedade em",
  "Compare itens para compor",
  "Veja caminhos para encontrar",
  "Descubra possibilidades de escolha em",
  "Conheça opções para analisar em",
  "Explore seleções para seu dia a dia em",
  "Compare opções para cada aplicação em",
  "Veja mais alternativas de",
  "Descubra linhas que atendem",
  "Conheça soluções para comparar com calma em",
  "Explore categorias que ajudam a escolher",
  "Compare opções para encontrar o melhor encaixe em",
  "Veja coleções pensadas para",
  "Descubra opções que ampliam suas escolhas em",
  "Conheça a variedade disponível em",
  "Explore soluções para diferentes cenários em",
  "Compare possibilidades antes de decidir em",
  "Veja opções para buscar",
  "Descubra caminhos para comprar melhor em",
  "Conheça alternativas relevantes de",
] as const;
