export type OrganizationMemberRole =
  | "owner"
  | "manager"
  | "salesperson"
  | "operator"
  | "cashier"
  | "finance"
  | "shipping"
  | "customer";

export type TblBoletoBancario = {
  ID_BOLETO: number;
  DT_CADASTRO?: Date | null;
};

export type TblCaixaLancamento = {
  ID_TBL_CAIXA_LANCAMENTO: number;
  ID_GENERATED?: number | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_STATUS?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_LOJA?: number | null;
  CM7?: string | null;
  NOME?: string | null;
  DESCRICAO?: string | null;
  VALOR?: number | null;
  COMPENSAR?: Date | null;
  CANCELADO?: number | null;
  TIPO?: string | null;
  ID_PEDIDO?: number | null;
  ID_CLIENTE?: number | null;
  ID_USUARIO?: number | null;
  ID_PROTOCOLO?: number | null;
  ID_VENDEDOR?: number | null;
  ID_SETOR?: number | null;
  DATA?: Date | null;
  HORA?: Date | null;
  ID_GERADO?: number | null;
  DATA_VENCIMENTO?: Date | null;
  QT?: number | null;
  ID_PRODUTO?: number | null;
  FLAG_CANTINA?: number | null;
  NF_NUMERO?: number | null;
  NF_LOTE?: number | null;
  NF_SERIE?: number | null;
  NF_STATUS?: string | null;
  NF_CHAVE?: string | null;
  NF_INFORMACAO?: string | null;
  NF_RETORNO?: string | null;
  NF_VALOR?: number | null;
  ID_CEDENTE?: number | null;
  TIPO_LANCAMENTO?: string | null;
  OK?: number | null;
  VALOR_DOC?: number | null;
  PG_DATA?: Date | null;
  PG_HORA?: Date | null;
  PG_ID_USUARIO?: number | null;
  PG_TIPO?: string | null;
  PG_DESCRICAO?: string | null;
  DOC_ESPECIE?: string | null;
  DOC_NUMERO?: number | null;
  INTEGRACAO?: string | null;
  ID_LOTE?: number | null;
  PATH?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  DT_CADASTRO?: Date | null;
};

export type TblCarrinho = {
  ID_CARRINHO: number;
  UUID?: string | null;
  ID_SYSTEM?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_PEDIDO?: number | null;
  TYPE_BUSINESS?: number | null;
  IP?: string | null;
  CEP?: string | null;
  STATUS_CART?: string | null;
  TIPO_FRETE?: string | null;
  TIPO?: string | null;
  PG_FORMA?: string | null;
  VL_FRETE?: number | null;
  VL_DESCONTO?: number | null;
  INATIVO?: number | null;
  CLOSETEDAT?: Date | null;
  UPDATEDAT?: Date | null;
  CREATEDAT?: Date | null;
  ANOTACOES?: string | null;
};

export type TblCarrinhoMovimento = {
  ID_MOVIMENTO: number;
  UUID?: string | null;
  ID_SYSTEM?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  TYPE_BUSINESS?: number | null;
  ID_CARRINHO?: number | null;
  ID_PRODUTO?: number | null;
  QT?: number | null;
  INATIVO?: number | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
  ANOTACOES?: string | null;
};

export type TblCategoria = {
  ID_CATEGORIA: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  CATEGORIA?: string | null;
  NIVEL?: number | null;
  ID_TBL_CADASTRO_TAXONOMIA?: number | null;
  PARENT_ID?: number | null;
  ID_TAXONOMIA?: number | null;
  TAXONOMIA?: string | null;
  PATH_IMAGEM?: string | null;
  ID_IMAGEM?: number | null;
  PATH_PAGE?: string | null;
  DATADOCADASTRO?: Date | null;
  DT_ALTERACAO?: Date | null;
  ORDEM?: number | null;
  QT_PRODUTOS?: number | null;
  QT_PRODUTOS_MOVIMENTACAO?: number | null;
  QT_PRODUTOS_ATIVOS?: number | null;
  QT_PRODUTOS_INATIVOS?: number | null;
  QT_PRODUTOS_TODOS?: number | null;
  INATIVO?: number | null;
  ANOTACOES?: string | null;
  FLAG_WEBSITE?: number | null;
  FLAG_COMPRAS?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblCategoriaRel = {
  ID_CATEGORIA: number;
  ID_PRODUTO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblCupom = {
  ID_CUPOM: number;
  CUPOM?: string | null;
  TX_DESC?: number | null;
  START_DATE?: Date | null;
  END_DATE?: Date | null;
  DT_CREATED?: Date | null;
  DT_UPDATED?: Date | null;
};

export type TblDepartamento = {
  ID_DEPARTAMENTO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  DEPARTAMENTO?: string | null;
  INATIVO?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblEntrada = {
  ID_TBL_ENTRADA: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_FORNECEDOR?: number | null;
  ID_PESSOA?: number | null;
  NUMERODANOTA?: string | null;
  MODELO?: string | null;
  ID_FRETE?: number | null;
  ID_TIPO?: number | null;
  ID_FRETADOR?: number | null;
  ID_PEDIDO?: number | null;
  DESCRICAO?: string | null;
  DATA_ENTRADA_ESTOQUE?: Date | null;
  HORA_ENTRADA_ESTOQUE?: Date | null;
  CAMBIO?: number | null;
  VL_TOTAL_NOTA?: number | null;
  VL_FRETE?: number | null;
  VL_TOTAL_PRODUTO?: number | null;
  IPI?: number | null;
  ICMS?: number | null;
  ID_EMPRESA?: number | null;
  ESTOQUE?: number | null;
  FISICO?: number | null;
  ETIQUETA?: number | null;
  TX_FRETE?: number | null;
  ANOTACOES?: string | null;
  HR_LANCAMENTO?: Date | null;
  DT_LANCAMENTO?: Date | null;
  DATADOCADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblEntradaMovimento = {
  ID_TBL_ENTRADA_MOVIMENTO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_ENTRADA: number;
  ID_TBL_PRODUTO?: number | null;
  ID_FORNECEDOR?: number | null;
  ID_FRETADOR?: number | null;
  ID_PRODUTO_TRANSF?: number | null;
  ID_GENERATED?: number | null;
  QT?: number | null;
  QT_COMPRADA?: number | null;
  QT_RECEBIDA?: number | null;
  PRODUTO?: string | null;
  REF_FORNECEDOR?: string | null;
  VL_NOTA: number;
  VL_UNIT_DOLAR?: number | null;
  VL_UNIT_REAL?: number | null;
  VL_FRETE_REAL?: number | null;
  VL_FRETE_DOLAR?: number | null;
  VL_IPI: number;
  VL_ICMS: number;
  VL_ST: number;
  VL_CUSTO?: number | null;
  VL_CUSTOREAL?: number | null;
  TX_CUSTO?: number | null;
  VL_VENDA?: number | null;
  CAMBIO?: number | null;
  PORCENT?: number | null;
  ESTOQUE?: number | null;
  FLUXO?: number | null;
  DATA?: Date | null;
  HORA?: Date | null;
  DATADOCADASTRO?: Date | null;
  IMPRESSAO?: number | null;
  ID_PRODUTO_FORNECEDOR?: string | null;
  CST?: string | null;
  CFOP?: string | null;
  ID_EMPRESA?: number | null;
  IPI?: number | null;
  ICMS?: number | null;
  VL_VENDA_ATACADO?: number | null;
  VL_VENDA_VAREJO?: number | null;
  TX_PRODUTO_LUCROATACADO?: number | null;
  TX_PRODUTO_LUCROVAREJO?: number | null;
  TX_PRODUTO_LUCROCORPORATIVO?: number | null;
  TX_PRODUTO_CUSTOREAL?: number | null;
  NCM?: string | null;
  ORIGEM?: number | null;
  BASE_ICMS?: number | null;
  BASE_IPI?: number | null;
  BASE_ST?: number | null;
  VL_TOTAL_IMPOSTO?: number | null;
  VL_ULTIMO_CUSTO?: number | null;
  TX_VARIACAO?: number | null;
  VL_VENDA_CORPORATIVO?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblEquipamento = {
  ID_EQUIPAMENTO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_PEDIDO?: number | null;
  ID_CLIENTE?: number | null;
  ID_USUARIO?: number | null;
  ID_TIPO?: number | null;
  ID_MODELO?: number | null;
  ID_MARCA?: number | null;
  DT_CADASTRO?: Date | null;
  TIPO?: string | null;
  EQUIPAMENTO?: string | null;
  MODELO?: string | null;
  MARCA?: string | null;
  SETOR?: string | null;
  PATRIMONIO?: string | null;
  SERIAL?: string | null;
  SERIAL2?: string | null;
  SERIALCOMP1?: string | null;
  SERIALCOMP2?: string | null;
  ANOTACOES?: string | null;
  DT_TERMINO?: Date | null;
  ID_STATUS?: number | null;
  DT_ENTREGA?: Date | null;
  ID_STATUS_SERVICO?: number | null;
  TECNICO?: string | null;
  SERIAL_NUMBER?: string | null;
  SERIAL_NUMBER2?: string | null;
  STATUS?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblFinanceiroCedente = {
  ID_FINANCEIRO_CEDENTE: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  DATADOCADASTRO?: Date | null;
  NOME?: string | null;
  CATEGORIA?: string | null;
  MODELO?: string | null;
  DATA_CONTRATO?: Date | null;
  DATA_TERMINO?: Date | null;
  OBSERVACOES?: string | null;
  ATIVO?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  CNPJ?: string | null;
};

export type TblFinanceiroMovimento = {
  ID_MOVIMENTO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  UUID?: number | null;
  ID_USUARIO?: number | null;
  ID_CLIENTE?: number | null;
  ID_VENDEDOR?: number | null;
  ID_PEDIDO?: number | null;
  ID_PEDIDO_MOVIMENTO?: number | null;
  ID_STATUS?: number | null;
  VALOR_MOVIMENTO?: number | null;
  VALOR_DEBITO?: number | null;
  VALOR_CREDITO?: number | null;
  VALOR_REGISTRO?: number | null;
  ID_TIPO?: number | null;
  MOTIVO?: string | null;
  FLAG_PROCESSADO?: number | null;
  FLAG_INATIVO?: number | null;
  NOTAS?: string | null;
  DT_VENCIMENTO?: Date | null;
  DT_UPDATE?: Date | null;
  DT_CADASTRO?: Date | null;
};

export type TblFinanceiroPgFormas = {
  ID_PG_FORMAS: number;
  ID_SYSTEM_CLIENTE: number;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  DESCRICAO?: string | null;
  ID_GRUPO?: number | null;
  ID_LOCALIZACAO?: number | null;
  TAXA?: number | null;
  INATIVO?: number | null;
  TX_FINANCEIRA?: number | null;
  TX_FINANCEIRA_ATAC?: number | null;
  TX_FINANCEIRA_VARE?: number | null;
  TX_DESCONTO?: number | null;
  TX_DESCONTO_ATAC?: number | null;
  TX_DESCONTO_VARE?: number | null;
  QT_PARCELA?: number | null;
  FATOR_ATAC?: number | null;
  FATOR_VARE?: number | null;
  FLAG_TX_PRODUTO?: number | null;
  PADRAO_LOJA_FISICA?: number | null;
  PADRAO_ECOMMERCE?: number | null;
  INDISPONIVEL_ATACADO?: number | null;
  INDISPONIVEL_VAREJO?: number | null;
  FLAG_APLICAR_DESCONTO?: number | null;
  ORDEM?: number | null;
  DATADOCADASTRO?: Date | null;
  ANOTACOES?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblFornecedor = {
  ID_FORNECEDOR: number;
  ID_SYSTEM_CLIENTE?: number | null;
  UUID?: string | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_CATEGORIA?: number | null;
  ID_TIPO?: number | null;
  ID_IMAGEM?: number | null;
  NOME?: string | null;
  FISIJURI?: string | null;
  FONE1?: string | null;
  FONE2?: string | null;
  WHATAPP1?: string | null;
  WHATAPP2?: string | null;
  CONTATO1?: string | null;
  CONTATO2?: string | null;
  SETOR1?: string | null;
  SETOR2?: string | null;
  EMAIL1?: string | null;
  EMAIL2?: string | null;
  RAZAO_SOCIAL?: string | null;
  CNPJ?: string | null;
  INSC_ESTADUAL?: string | null;
  INSC_MUNICIPAL?: string | null;
  NOME_FANTASIA?: string | null;
  DATA_CNPJ?: Date | null;
  NOME_RESPONSAVEL?: string | null;
  CARGO_RESPOSNAVEL?: string | null;
  ATIVIDADE_PRINCIPAL?: string | null;
  ATIVIDADES_SECUNDARIA1?: string | null;
  ATIVIDADES_SECUNDARIA2?: string | null;
  ATIVIDADES_SECUNDARIA3?: string | null;
  ATIVIDADES_SECUNDARIA4?: string | null;
  ATIVIDADES_SECUNDARIA5?: string | null;
  NATUREZA_JURIDICA?: string | null;
  OBJETIVO_MISSAO?: string | null;
  MISSAO_VISAO?: string | null;
  PRIMEIRO_NOME?: string | null;
  CARGO?: string | null;
  ID_RESPONSAVEL?: number | null;
  CPF?: string | null;
  RG?: string | null;
  GENERO?: string | null;
  SOBRENOME?: string | null;
  NOME_DO_MEIO?: string | null;
  TRATAMENTO?: string | null;
  TRABALHANAEMPRESA?: string | null;
  FORMACAOACADEMICA?: string | null;
  FORMACAOATUAL?: string | null;
  ESPECIALIZACAO?: string | null;
  INSTITUICAODEENSINO?: string | null;
  CONJUGUE?: string | null;
  DATADONASCIMENTO?: Date | null;
  CEP?: string | null;
  ENDERECO?: string | null;
  ENDERECO_NUMERO?: string | null;
  COMPLEMENTO?: string | null;
  BAIRRO?: string | null;
  CIDADE?: string | null;
  UF?: string | null;
  REGIAO_PAIS?: string | null;
  PAIS?: string | null;
  COD_MUNICIPIO?: number | null;
  COD_UF?: number | null;
  WEBSITE?: string | null;
  SKYPE?: string | null;
  FACEBOOK?: string | null;
  TWITTER?: string | null;
  FRETADOR?: number | null;
  DT_ULTIMA_COMPRA?: Date | null;
  DATADOCADASTRO?: Date | null;
  ANOTACOES?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblHistPedido = {
  ID_HISTORICO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_PEDIDO: number;
  ID_USUARIO?: number | null;
  ID_CLIENTE?: number | null;
  ID_VENDEDOR?: number | null;
  ID_LOCATION?: number | null;
  ID_PG_FORMA?: number | null;
  ID_STATUS_ORCAMENTO?: number | null;
  ID_STATUS_PEDIDO?: number | null;
  ID_STATUS_FINANCEIRO?: number | null;
  ID_STATUS_ESTOQUE?: number | null;
  ID_STATUS_ENTREGA?: number | null;
  ID_LOCALIZACAO_PED?: number | null;
  HISTORICO?: string | null;
  OPERACAO?: string | null;
  USUARIO?: string | null;
  VL_ACRESCIMO?: number | null;
  CODIGOP?: string | null;
  ID_PROTOCOLO?: number | null;
  QT_PARCELA?: number | null;
  VL_FRETE?: number | null;
  VL_DESCONTO?: number | null;
  VL_PARCELA?: number | null;
  VL_TOTAL_PARCELADO?: number | null;
  DATADOCADASTRO?: Date | null;
  ID_STATUS?: number | null;
  NOTA?: string | null;
  DATAHORA?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblHistPedidoMov = {
  ID_PED_MOV_HIST: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_MOVIMENTO?: number | null;
  ID_PEDIDO?: number | null;
  ID_CLIENTE?: number | null;
  ID_VENDEDOR?: number | null;
  ID_USUARIO?: number | null;
  ID_PRODUTO?: number | null;
  ID_PG_FORMA?: number | null;
  QT?: number | null;
  OPERACAO?: string | null;
  HISTORICO?: string | null;
  USUARIO?: string | null;
  DESCRICAO?: string | null;
  ID_STATUS_PEDIDO?: string | null;
  VL_UNITARIO?: number | null;
  VL_DESCONTO?: number | null;
  VL_DESCONTO_ADM?: number | null;
  QT_ESTORNADA?: number | null;
  STATUS?: string | null;
  DT_ESTORNO?: Date | null;
  DT_EXCLUIDO?: Date | null;
  ESTORNO?: number | null;
  PROMOCAO?: number | null;
  DATADOCADASTRO?: Date | null;
  ANOTACOES?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblHistProdEstoque = {
  ID_HIST_ESTOQUE: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_PRODUTO?: number | null;
  STQ_ANTERIOR?: number | null;
  STQ_ADICIONADO?: number | null;
  STQ_SUBTRAIDO?: number | null;
  STQ_ALTERADO?: number | null;
  STQ_DEPOIS?: number | null;
  OPERACAO?: string | null;
  LOJA?: string | null;
  USUARIO?: string | null;
  ID_ENTRADA?: number | null;
  ID_PEDIDO?: number | null;
  HISTORICO?: string | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblHistProdFisico = {
  ID_HISTORICO_FISICO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_TBL_PRODUTO_FISICO: number;
  ID_PRODUTO?: number | null;
  ID_ENTRADA?: number | null;
  ID_ENTRADA_MOVIMENTO?: number | null;
  ID_PEDIDO?: number | null;
  ID_PEDIDO_MOVIMENTO?: number | null;
  ID_CLIENTE?: number | null;
  ID_LOCALIZACAO?: number | null;
  ID_EMPRESA?: number | null;
  ID_STATUS?: number | null;
  ID_USUARIO?: number | null;
  DATA?: Date | null;
  ESTOQUE?: number | null;
  VL_CUSTO?: number | null;
  HISTORICO?: string | null;
  USUARIO?: string | null;
  PRODUTO?: string | null;
  COD_BARRAS?: string | null;
  N_SERIE?: string | null;
  NF_ENTRADA?: string | null;
  NF_SAIDA?: string | null;
  SERVER?: string | null;
  GARANTIA?: Date | null;
  ESTORNO?: number | null;
  RMA?: number | null;
  FINAL_GARANTIA?: number | null;
  DATA_RETIRADA?: Date | null;
  HORA_RETIRADA?: Date | null;
  DT_PEDIDO?: Date | null;
  DT_ESTORNO?: Date | null;
  VL_VENDA?: number | null;
  ID_VENDEDOR?: number | null;
  DT_RETIRADA?: Date | null;
  HORA?: Date | null;
  ID_HISTORICO?: number | null;
  ID_STATUSRMA?: number | null;
  TAMANHO?: string | null;
  MARCA?: string | null;
  DT_CADASTRO?: Date | null;
  DESCRICAO?: string | null;
  FLAG_IMP_HIST?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblHistProdPreco = {
  ID_HIST_PRECO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_PRODUTO?: number | null;
  HISTORICO?: string | null;
  LOJA?: string | null;
  USUARIO?: string | null;
  OPERACAO?: string | null;
  VL_ATACADO?: number | null;
  VL_CORPORATIVO?: number | null;
  VL_VAREJO?: number | null;
  VL_OURO?: number | null;
  VL_PRATA?: number | null;
  VL_BRONZE?: number | null;
  DECONTO1?: number | null;
  DECONTO2?: number | null;
  DECONTO3?: number | null;
  QUANTIDADE1?: number | null;
  QUANTIDADE2?: number | null;
  QUANTIDADE3?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblKeyvalor = {
  ID_KEYVALOR: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_PARENT?: number | null;
  ID_ORDER?: number | null;
  ID_TIPO?: number | null;
  ID_CATEGORIA?: number | null;
  ID_MODULO?: number | null;
  ID_CADASTRO?: number | null;
  ID_RESPONSAVEL?: number | null;
  ID_STATUS?: number | null;
  CHAVE?: string | null;
  VALOR?: string | null;
  NOTAS?: string | null;
  INATIVO?: number | null;
  DT_FINAL?: Date | null;
  DT_INICIO?: Date | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblKeyvalorCategoria = {
  ID_CATEGORIA: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_ORDER?: number | null;
  ID_PARENT?: number | null;
  ID_TIPO?: number | null;
  ID_MODULO?: number | null;
  CATEGORIA?: string | null;
  NOTAS?: string | null;
  INATIVO?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblLocalizacao = {
  ID_TBL_LOCALIZACAO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  DESCRICAO?: string | null;
  SETOR?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblLogOperation = {
  id: number;
  APP_ID?: number | null;
  SYSTEM_CLIENT_ID?: number | null;
  ORGANIZATION_ID?: string | null;
  USER_ID?: string | null;
  USER_NAME?: string | null;
  USER_ROLE?: string | null;
  PERSON_ID?: number | null;
  ID_USUARIO?: number | null;
  ID_MODULE?: number | null;
  ID_CADASTRO?: number | null;
  LOG?: string | null;
  NOTE?: string | null;
  CREATEDAT?: Date | null;
};

export type TblLoja = {
  ID_LOJA: number;
  ID_SYSTEM_CLIENTE: number;
  ID_SYSTEM?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  NOME?: string | null;
  PATH_LOGO01?: string | null;
  CABECALHO_IMPRESSAO?: string | null;
  DOMINIO?: string | null;
  WOO_KEY?: string | null;
  WOO_SECRET?: string | null;
  FLAG_REVENDA?: number | null;
  WEBSITE?: string | null;
  PATH_IMAGEM01?: string | null;
  INATIVO?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblModulo = {
  ID_TBL_MODULO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  NOMEDOMODULO?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblPedido = {
  ID_TBL_PEDIDO: number;
  ID_GENERATED?: number | null;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_TBL_CLIENTE?: number | null;
  ID_TBL_VENDEDOR?: number | null;
  ID_TBL_TABELA?: number | null;
  ID_TBL_PROTOCOLO?: number | null;
  ID_PROTOCOLO?: number | null;
  ID_TBL_ENTREGA?: number | null;
  ID_TBL_PEDIDO_IP?: number | null;
  ID_TBL_USUARIO?: number | null;
  ID_ORDER?: number | null;
  ID_LOCATION?: number | null;
  ID_LOCALIZACAO_PED?: number | null;
  ID_STATUS_PEDIDO?: number | null;
  ID_STATUS_FINANCEIRO?: number | null;
  ID_STATUS_ENTREGA?: number | null;
  ID_STATUS_ESTOQUE?: number | null;
  ID_TIPO_FRETE?: number | null;
  ID_FORMATO_ENVIO?: number | null;
  ID_LOJA?: number | null;
  ID_TIPO?: number | null;
  ID_STATUS_ORCAMENTO?: number | null;
  ID_STATUS_RMA?: number | null;
  ID_PG_FORMA?: number | null;
  ID_FRM_ENTREGA?: number | null;
  ID_RMA?: number | null;
  ID_CARRINHO?: number | null;
  PRN?: number | null;
  PRAZO_ENTREGA_DIA?: number | null;
  QT_VOLUME?: number | null;
  QT_PARCELA?: number | null;
  VL_FRETE_ENTREGA?: number | null;
  PESO_FRETE_GR?: number | null;
  ALTURA_VOLUME?: number | null;
  LARGURA_VOLUME?: number | null;
  COMPRIMENTO_VOLUME?: number | null;
  ID_EQUIPAMENTO?: number | null;
  ID_TIPO_ENTREGA?: number | null;
  DATAENVIO_FRETE?: Date | null;
  DATAENTREGA_FRETE?: Date | null;
  USUARIO_ESTOQUE?: string | null;
  PRIORIDADE?: string | null;
  CODIGO_CORREIOS?: string | null;
  USUARIO_ESTORNO?: string | null;
  STATUS_PEDIDO?: string | null;
  STATUS_FINANCEIRO?: string | null;
  STATUS_ENTREGA?: string | null;
  USUARIO?: string | null;
  STATUS_ESTOQUE?: string | null;
  USUARIO_ENTREGA?: string | null;
  CODIGOP?: string | null;
  TX_DESCONTO_CODP?: number | null;
  VL_FATOR?: number | null;
  TX_PG_FINANCEIRA?: number | null;
  TX_PG_DESCONTO?: number | null;
  VL_FRETE?: number | null;
  VL_DESCONTO?: number | null;
  VL_ACRESCIMO?: number | null;
  VL_PARCELA?: number | null;
  INATIVO?: number | null;
  FLAG_VENDA_ATACADO?: number | null;
  QT_ESTORNADA?: number | null;
  DATA?: Date | null;
  HORA?: Date | null;
  DATA_LIBERACAO?: Date | null;
  DATA_VENDA?: Date | null;
  DATA_PEDIDO?: Date | null;
  DATA_ESTORNO?: Date | null;
  DATA_RETIRADA?: Date | null;
  DATA_PAGAMENTO?: Date | null;
  DATA_ESTOQUE?: Date | null;
  DATA_VALIDADE_ORC?: Date | null;
  DATA_ORCAMENTO?: Date | null;
  DATADOCADASTRO?: Date | null;
  OBSERVACOES?: string | null;
  ANOTACOES?: string | null;
  ID_USUARIO_ENTREGA?: number | null;
  DATA_ENTREGA?: Date | null;
  DT_VENDA_FINAL?: Date | null;
  ENTRADA?: string | null;
  ID_FISICO_RMA?: number | null;
  DEFEITO?: string | null;
  LAUDO?: string | null;
  NFE_CHAVE?: string | null;
  NFE_LOTE?: number | null;
  NFE_NUMERO?: number | null;
  NFE_OPERACAO?: string | null;
  NFE_CHAVE_DEVOLUCAO?: string | null;
  EQUIPAMENTO?: string | null;
  MODELO?: string | null;
  SERIAL?: string | null;
  TECNICO?: string | null;
  CUPOM?: string | null;
  ID_STATUS_OS?: number | null;
  STATUS_OS?: string | null;
  TERCEIRIZADO?: string | null;
  DT_TRANFERENCIA?: Date | null;
  NFSE?: number | null;
  FLAG_COMISSAO?: number | null;
  ID_TRANSPORTADORA?: number | null;
  INFO_NOTAFISCAL?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  ID_CART?: number | null;
};

export type TblPedidoConfig = {
  ID_PEDIDO_CONFIG: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_LOCATION?: number | null;
  ID_VENDEDOR?: number | null;
  ID_ST_ORCAMENTO?: number | null;
  ID_ST_PEDIDO?: number | null;
  ID_ST_ENTREGA?: number | null;
  ID_ST_ESTOQUE?: number | null;
  ID_ST_FINANCEIRO?: number | null;
  ID_PG_FORMA?: number | null;
  ID_TP_FRETE?: number | null;
  ID_FM_ENVIO?: number | null;
  AJUSTE_MINIMO?: number | null;
  PZ_ENTREGA_DIA?: number | null;
  PZ_VALIDADE_DIA?: number | null;
  VL_DELIVERY?: number | null;
  DT_CADASTRO?: Date | null;
  OBSERVACOES?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblPedidoMovimento = {
  ID_TBL_PEDIDO_MOVIMENTO: number;
  ID_GENERATED?: number | null;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_TBL_PEDIDO?: number | null;
  ID_TBL_USUARIO?: number | null;
  ID_TBL_PRODUTO?: number | null;
  ID_TBL_PROTOCOLO?: number | null;
  ID_PROTOCOLO?: number | null;
  ID_MARCA?: number | null;
  ID_TIPO?: number | null;
  ID_CLIENTE?: number | null;
  ID_FAMILIA?: number | null;
  ID_GRUPO?: number | null;
  ID_SUBGRUPO?: number | null;
  ID_VENDEDOR?: number | null;
  ID_FISICO?: number | null;
  ID_RMA?: number | null;
  ID_PG_FORMA?: number | null;
  ID_MOVIMENTO_WEB?: string | null;
  QT?: number | null;
  QT_ESTORNADA?: number | null;
  ID_EQUIPAMENTO?: number | null;
  VL_UNITARIO?: number | null;
  VL_TOTAL?: number | null;
  VL_DESCONTO?: number | null;
  VL_DESCONTO_ADM?: number | null;
  VL_FRETE?: number | null;
  VL_UNITARIO_REF?: number | null;
  VL_CUSTO_PRODUTO?: number | null;
  ICMS_BC?: number | null;
  ICMS_VALOR?: number | null;
  ICMS_ALIQUOTA?: number | null;
  ST_BC?: number | null;
  ST_VALOR?: number | null;
  ST_ALIQUOTA?: number | null;
  IPI_BC?: number | null;
  IPI_VALOR?: number | null;
  IPI_ALIQUOTA?: number | null;
  VL_NFE_DESC?: number | null;
  VL_DESPESAS_ADICIONAIS?: number | null;
  VL_SEGURO?: number | null;
  VL_ACRESCIMO?: number | null;
  DESCRICAO?: string | null;
  STATUS_EXPEDICAO?: string | null;
  SETOR_RMA?: string | null;
  STATUS?: string | null;
  CODIGOP?: string | null;
  MODELO?: string | null;
  PROMO?: number | null;
  ESTORNO?: number | null;
  PROMOCAO?: number | null;
  INATIVO?: number | null;
  HORA?: Date | null;
  DATA?: Date | null;
  DATADOCADASTRO?: Date | null;
  DT_ESTORNO?: Date | null;
  DT_RETORNO?: Date | null;
  DT_EXPEDICAO?: Date | null;
  ENTRADA?: string | null;
  ANOTACOES?: string | null;
  QT_FISICA_EXPEDIDA?: number | null;
  FLAG_EMISSAO?: number | null;
  CFOP?: string | null;
  CST?: string | null;
  IPI_CENQ?: string | null;
  IPI_CST?: string | null;
  NUMERO_NFE?: number | null;
  GARANTIA_DIAS?: number | null;
  VL_ATACADO?: number | null;
  VL_CORPORATIVO?: number | null;
  VL_VAREJO?: number | null;
  VL_OURO?: number | null;
  VL_PRATA?: number | null;
  VL_BRONZE?: number | null;
  TXT_DESC1?: string | null;
  TXT_DESC2?: string | null;
  TXT_DESC3?: string | null;
  VL_DESC1?: number | null;
  VL_DESC2?: number | null;
  VL_DESC3?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  ESTOQUE_MINIMO?: number | null;
  ESTOQUE_ATUAL?: number | null;
  VLT_TX_VENDA?: number | null;
  VLT_TX_MKT?: number | null;
  VLT_TX_TI?: number | null;
  ID_CART?: number | null;
  ID_CART_MOV?: number | null;
};

export type TblPedidoTipoFrete = {
  ID_TIPO_FRETE: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  TIPO_FRETE?: string | null;
  VALOR_PADRAO?: number | null;
  TAXA_PADRAO?: number | null;
  INATIVO?: number | null;
  DATADOCADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblPessoa = {
  ID_TBL_PESSOA: number;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_CONSUMER?: number | null;
  ID_PARENTS?: number | null;
  ID_PESSOA_CATEGORIA?: number | null;
  ID_PESSOA_TIPO?: number | null;
  ID_MODULO?: number | null;
  ID_TBL_PRODUTO_TAXA?: number | null;
  TIPO_DE_PESSOA?: string | null;
  FISIJURI?: string | null;
  NOME?: string | null;
  ID_IMAGEM?: number | null;
  PATH_IMAGEM?: string | null;
  FONE1?: string | null;
  FONE2?: string | null;
  FONE3?: string | null;
  FONE4?: string | null;
  FONE5?: string | null;
  FAX?: string | null;
  EMAIL?: string | null;
  EMAIL2?: string | null;
  EMAIL3?: string | null;
  EMAIL4?: string | null;
  EMAIL5?: string | null;
  INDEFINIDO?: string | null;
  INATIVO?: number | null;
  CLIENTE?: number | null;
  FORNECEDOR?: number | null;
  PROFISSIONAL?: number | null;
  FUNCIONARIO?: number | null;
  VENDEDOR?: number | null;
  USUARIO?: number | null;
  PESSOA?: number | null;
  AFILIADO?: number | null;
  WHATAPP1?: string | null;
  WHATAPP2?: string | null;
  WHATAPP3?: string | null;
  WHATAPP4?: string | null;
  WHATAPP5?: string | null;
  CONTATO1?: string | null;
  CONTATO2?: string | null;
  CONTATO3?: string | null;
  CONTATO4?: string | null;
  CONTATO5?: string | null;
  SETOR1?: string | null;
  SETOR2?: string | null;
  SETOR3?: string | null;
  SETOR4?: string | null;
  SETOR5?: string | null;
  RAMAL1?: string | null;
  RAMAL2?: string | null;
  RAMAL3?: string | null;
  RAMAL4?: string | null;
  RAMAL5?: string | null;
  WEBSITE?: string | null;
  SKYPE?: string | null;
  ANOTACOES?: string | null;
  FACEBOOK?: string | null;
  TWITTER?: string | null;
  LINKEDIN?: string | null;
  DATADOCADASTRO?: Date | null;
  LOGIN?: string | null;
  SENHA?: string | null;
  ACESSOWEBADMIN?: number | null;
  ACESSOWEB?: number | null;
  ACESSODESK?: number | null;
  NIVEL?: number | null;
  ROLE?: number | null;
  PRINT_INDEX?: number | null;
  PRN_TERMICA?: string | null;
  PRN_CODBARRAS?: string | null;
  PRN_PADRAO?: string | null;
  PRN_PDV?: string | null;
  PRN_FISCAL?: string | null;
  PRN_CODBARRAS1?: string | null;
  PRN_CODBARRAS2?: string | null;
  EMAIL_DE_LOGIN?: string | null;
  ID_TIPO_CLIENTE?: number | null;
  ID_STATUS_CLIENTE?: number | null;
  ID_STATUS_REVENDA?: number | null;
  ID_VENDEDOR?: number | null;
  ID_CARRINHO?: number | null;
  APROVADO?: string | null;
  EMAIL_MKT?: number | null;
  RESTRICAO?: number | null;
  DT_ULTIMA_COMPRA?: Date | null;
  CEP?: string | null;
  ENDERECO?: string | null;
  ENDERECO_NUMERO?: string | null;
  COMPLEMENTO?: string | null;
  BAIRRO?: string | null;
  CIDADE?: string | null;
  UF?: string | null;
  REGIAO_PAIS?: string | null;
  PAIS?: string | null;
  COD_MUNICIPIO?: number | null;
  COD_UF?: number | null;
  PRIMEIRO_NOME?: string | null;
  NOME_DO_MEIO?: string | null;
  SOBRENOME?: string | null;
  GENERO?: string | null;
  TRATAMENTO?: string | null;
  CPF?: string | null;
  RG?: string | null;
  TRABALHANAEMPRESA?: string | null;
  CARGO?: string | null;
  FORMACAOACADEMICA?: string | null;
  FORMACAOATUAL?: string | null;
  ESPECIALIZACAO?: string | null;
  INSTITUICAODEENSINO?: string | null;
  CONJUGUE?: string | null;
  FLAG_WEB?: number | null;
  DATADONASCIMENTO?: Date | null;
  NOMEDOPAI?: string | null;
  NOMEDAMAE?: string | null;
  CPFDOPAI?: string | null;
  CPFDAMAE?: string | null;
  ESCOLANOME?: string | null;
  DADOSDAFORMACAO?: string | null;
  ANOTACOES_PF?: string | null;
  ANOTACOES_PJ?: string | null;
  ANOTACOES_ENDERECO?: string | null;
  ANOTACOES_CLIENTE?: string | null;
  ANOTACOES_VENDEDOR?: string | null;
  RAZAO_SOCIAL?: string | null;
  NOME_FANTASIA?: string | null;
  CNPJ?: string | null;
  DATA_CNPJ?: Date | null;
  INSC_ESTADUAL?: string | null;
  INSC_MUNICIPAL?: string | null;
  NOME_RESPONSAVEL?: string | null;
  CARGO_RESPONSAVEL?: string | null;
  ATIVIDADE_PRINCIPAL?: string | null;
  ATIVIDADES_SECUNDARIA1?: string | null;
  ATIVIDADES_SECUNDARIA2?: string | null;
  ATIVIDADES_SECUNDARIA3?: string | null;
  ATIVIDADES_SECUNDARIA4?: string | null;
  ATIVIDADES_SECUNDARIA5?: string | null;
  NATUREZA_JURIDICA?: string | null;
  OBJETIVO_MISSAO?: string | null;
  MISSAO_VISAO?: string | null;
  VALOR_PERC_COMISSAO?: number | null;
  DT_ULT_ACESSO?: Date | null;
  DT_UPDATE?: Date | null;
  ID_PARENT?: number | null;
};

export type TblPessoaCategoria = {
  ID_TBL_PESSOA_CATEGORIA: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  CATEGORIA?: string | null;
  INATIVO?: number | null;
  DESCRICAO_CATEGORIA: string;
  DATADOCADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblPessoaConfig = {
  ID_PESSOA: number;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  JSON_CONFIG?: string | null;
  HR_INICIAL?: number | null;
  HR_FINAL?: number | null;
  FLAG_SEG?: number | null;
  FLAG_TER?: number | null;
  FLAG_QUA?: number | null;
  FLAG_QUI?: number | null;
  FLAG_SEX?: number | null;
  FLAG_SAB?: number | null;
  FLAG_DOM?: number | null;
  STATUS_ID?: string | null;
  PRINT_INDEX?: number | null;
  PRN_TERMICA?: string | null;
  PRN_CODBARRAS?: string | null;
  PRN_PADRAO?: string | null;
  PRN_PDV?: string | null;
  PRN_FISCAL?: string | null;
  PRN_CODBARRAS1?: string | null;
  PRN_CODBARRAS2?: string | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
  ID_THEMA?: number | null;
  EMAIL_NOTIFICATIONS?: number | null;
  SMS_NOTIFICATIONS?: number | null;
  WHATSAPP_NOTIFICATIONS?: number | null;
  PUSH_NOTIFICATIONS?: number | null;
};

export type TblPessoaInternet = {
  ID_PESSOA: number;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_FACEBOOK_LOGIN?: string | null;
  ID_GOOGLE_LOGIN?: string | null;
  ID_TWITTER_LOGIN?: string | null;
  ID_LINKEDIN_LOGIN?: string | null;
  WEBSITE?: string | null;
  FACEBOOK?: string | null;
  TWITTER?: string | null;
  LINKEDIN?: string | null;
  INSTAGRAM?: string | null;
  TIKTOK?: string | null;
  TELEGRAM?: string | null;
  NOTES?: string | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
};

export type TblPreposicao = {
  ID_PREPOSICAO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  PREPOSICAO?: string | null;
  PRIORIDADE?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblProductSlug = {
  ID_TBL_PRODUTO: number;
  PRODUTO?: string | null;
  SLUG?: string | null;
};

export type TblProductWoo = {
  product_id: number;
  post_id?: number | null;
  product_name?: string | null;
  product_url?: string | null;
  slug?: string | null;
  image_main?: string | null;
  image1?: string | null;
  image2?: string | null;
  image3?: string | null;
  image4?: string | null;
  image5?: string | null;
  carta_venda?: string | null;
  descricao?: string | null;
  createdat?: Date | null;
  flag_content?: number | null;
  updatedat?: Date | null;
  exportdat?: Date | null;
  flag_export?: number | null;
  srv_image1?: string | null;
  srv_image2?: string | null;
  srv_image3?: string | null;
  srv_image4?: string | null;
  srv_image5?: string | null;
  srv_image_main?: string | null;
};

export type TblProduto = {
  ID_TBL_PRODUTO: number;
  RECORD_ID_REV?: number | null;
  UUID?: string | null;
  APP_ID?: number | null;
  ID_GENERATED?: number | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_FABRICANTE?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_POST?: number | null;
  ID_MARCA?: number | null;
  ID_FORNECEDOR?: number | null;
  ID_FAMILIA?: number | null;
  ID_GRUPO?: number | null;
  ID_SUBGRUPO?: number | null;
  ID_STATUS_COMPRA?: number | null;
  ID_PARENT?: number | null;
  ID_IMAGEM?: number | null;
  ID_LOJA?: number | null;
  ID_TIPO?: number | null;
  ID_LOCALIZACAO?: number | null;
  ID_MODULO?: number | null;
  NCM?: number | null;
  QT_PARA_COMPRA?: number | null;
  TEMPODEGARANTIA_MES?: number | null;
  PESO_GR?: number | null;
  COMPRIMENTO_MM?: number | null;
  LARGURA_MM?: number | null;
  ALTURA_MM?: number | null;
  DIAMETRO_MM?: number | null;
  ID_FORMATO_ENVIO?: number | null;
  SKU?: string | null;
  TEMPO_ENTREGA_DIAS?: number | null;
  NAO_USAR_DOLAR?: number | null;
  PPB?: number | null;
  QT_VENDAS_ANO?: number | null;
  QT_VENDAS_MES?: number | null;
  QT_VENDAS_3MESES?: number | null;
  QT_VENDAS_ALL?: number | null;
  PRODUTO?: string | null;
  PRODUTO_BKP?: string | null;
  DESCRICAO_TAB?: string | null;
  FABRICANTE?: string | null;
  PATH_IMAGEM?: string | null;
  PATH_IMAGEM_VENDA?: string | null;
  PATH_PAGE?: string | null;
  PATH_WEBSITE_ATAC?: string | null;
  PATH_WEBSITE_VARE?: string | null;
  SLUG?: string | null;
  LINK_TITLE?: string | null;
  META_DESCRIPTION?: string | null;
  META_TITLE?: string | null;
  REF?: string | null;
  ETIQUETA?: string | null;
  SEGMENTO?: string | null;
  CFOP?: string | null;
  CST?: string | null;
  MODELO?: string | null;
  NBM?: string | null;
  EAN?: string | null;
  SALEUNIT?: string | null;
  NOME_ANTERIOR?: string | null;
  QT_SALEUNIT?: number | null;
  FLAG_SERVICO?: number | null;
  TX_TOTALBASE_ATACADO?: number | null;
  TX_TOTALBASE_VAREJO?: number | null;
  TEMP?: number | null;
  TX_LUCRO_VAREJO?: number | null;
  TX_LUCRO_ATACADO?: number | null;
  TX_DESCONTO_VAREJO?: number | null;
  TX_DESCONTO_ATACADO?: number | null;
  TX_COMISSAO_VAREJO?: number | null;
  TX_COMISSAO_ATACADO?: number | null;
  IPI?: number | null;
  ICMS?: number | null;
  VL_ST?: number | null;
  TX_ST?: number | null;
  TX_CUSTO?: number | null;
  TX_LUCRO?: number | null;
  TX_FRETE?: number | null;
  TAXA_PERCA?: number | null;
  VL_FRETE_REAL?: number | null;
  VL_FRETE_DOLAR?: number | null;
  VL_ENT_REAL?: number | null;
  VL_ENT_DOLAR?: number | null;
  VL_ENT_DOLAR_BKP?: number | null;
  VL_ENT_REAL_BKP?: number | null;
  VL_FRETE_DOLAR_BKP?: number | null;
  VL_FRETE_REAL_BKP?: number | null;
  FLAG_USAR_SN?: number | null;
  IMPORTADO?: number | null;
  CONSIGNADO?: number | null;
  INATIVO?: number | null;
  PROMOCAO?: number | null;
  LANCAMENTO?: number | null;
  DESCONTINUADO?: number | null;
  CONTROLAR_ESTOQUE?: number | null;
  DESTAQUE?: number | null;
  REPETIRETIQUETA?: number | null;
  FLAG_EXPORTADO?: number | null;
  FLAG_EXP_WEBSITE?: number | null;
  PRN_QTLACRE?: number | null;
  DATADOCADASTRO?: Date | null;
  DATA_ULT_ENTRADA?: Date | null;
  DATA_ULT_VENDA?: Date | null;
  DATA_ULT_UPDATE?: Date | null;
  DT_ALT_ESTOQUE?: Date | null;
  DT_MONITOR?: Date | null;
  DESCRICAO_VENDA?: string | null;
  DESCRICAO_COMPATIBILIDADE?: string | null;
  ANOTACOES?: string | null;
  INDEFINIDO?: string | null;
  QT_ETIQUETAS?: number | null;
  EXCLUIDO?: number | null;
  FLAG_LACRE_DESTRUTIVO?: number | null;
  FLAG_CONTROLE_FISICO?: number | null;
  FLAG_LOOP?: number | null;
  FLAG_REVENDA?: number | null;
  SOLICITACAO_VENDAS1?: number | null;
  SOLICITACAO_VENDAS2?: number | null;
  SOLICITACAO_VENDAS3?: number | null;
  SOLICITACAO_VENDAS4?: number | null;
  FLAG_IMG_HAYAMAX?: number | null;
  DT_EXPORTADO?: Date | null;
  FLAG_WEBSITE_OFF?: number | null;
  STQ_FILEIRA?: number | null;
  STQ_GONDULA?: number | null;
  LOCAL?: string | null;
  STQ_PRATELEIRA?: number | null;
  CST_SAIDA?: string | null;
  CEST?: number | null;
  DT_UPD_WEBSITE?: Date | null;
  FLAG_PERECIVEL?: number | null;
  QT_VENDAS_MEDIA3MESES?: number | null;
  QT_VENDAS_MEDIA12MESES?: number | null;
  NFE_CEST?: string | null;
  CFOP_SAIDA?: string | null;
  NFE_CFOP_SAIDA?: string | null;
  NFE_CST_CSOSN?: string | null;
  PATH_WEBSITE_TOPRIBEIRAO?: string | null;
  ID_EMISSAO?: number | null;
  TEMPODEGARANTIA_DIA?: number | null;
  LOCAL_ESTOQUE?: string | null;
  TXBASE_ATACADO?: number | null;
  TXBASE_CORPORATIVO?: number | null;
  TXBASE_VAREJO?: number | null;
  FLAG_REPOSICAO?: number | null;
  DT_REPOSICAO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  REF_BKP?: string | null;
  ETIQUETA_BKP?: string | null;
  INFO?: string | null;
  PATH_IMAGEM_BKP?: string | null;
  PATH_IMAGEM_SRV?: string | null;
  DESCRICAO_VENDA_BKP?: string | null;
  DESCRICAO_VENDA_SRV?: string | null;
  ANOTACOES_BKP?: string | null;
  ANOTACOES_SRV?: string | null;
};

export type TblProdutoCaracteristica = {
  ID_CARACTERISTICA: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_PRODUTO?: number | null;
  CARACTERISTICA?: string | null;
  VALOR?: string | null;
  INATIVO?: number | null;
  FLAG_CARAC_IMP?: number | null;
  DT_CADASTRO?: Date | null;
  ANOTACOES?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblProdutoConfig = {
  ID_CONFIG: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_FAMILIA?: number | null;
  ID_GRUPO?: number | null;
  ID_SUBGRUPO?: number | null;
  ID_FORNECEDOR?: number | null;
  ID_TIPO?: number | null;
  ID_MARCA?: number | null;
  TX_COMISSAO_ATACADO?: number | null;
  TX_COMISSAO_VAREJO?: number | null;
  TX_DESCONTO_ATACADO?: number | null;
  TX_DESCONTO_VAREJO?: number | null;
  TX_LUCRO_VAREJO?: number | null;
  TX_LUCRO_ATACADO?: number | null;
  CAMBIO?: number | null;
  NBM?: string | null;
  EAN?: string | null;
  PPB?: number | null;
  VL_ST?: number | null;
  ICMS?: number | null;
  IPI?: number | null;
  TEMP?: number | null;
  IVA?: number | null;
  PIS?: number | null;
  COFINS?: number | null;
  NBM2?: string | null;
  VL_VENDA_VAREJO?: number | null;
  VL_VENDA_ATACADO?: number | null;
  NCM?: number | null;
  NFE_CEST?: string | null;
  CFOP?: string | null;
  NFE_CFOP_SAIDA?: string | null;
  CST?: string | null;
  NFE_CST_CSOSN?: string | null;
  CFOP_SAIDA?: string | null;
  CEST?: number | null;
  CLAS_FISCAL?: string | null;
  INATIVO?: number | null;
  ANOTACOES?: string | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblProdutoEstoque = {
  ID_PRODUTO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_ULT_ENTRADA?: number | null;
  ESTOQUE_LOJA1?: number | null;
  ESTOQUE_LOJA2?: number | null;
  ESTOQUE_LOJA3?: number | null;
  ESTOQUE_LOJA4?: number | null;
  ESTOQUE_LOJA5?: number | null;
  ESTOQUE_LOJA6?: number | null;
  ESTOQUE_LOJA7?: number | null;
  ESTOQUE_LOJA8?: number | null;
  ESTOQUE_LOJA9?: number | null;
  ESTOQUE_LOJA10?: number | null;
  ESTOQUE_LOJA11?: number | null;
  ESTOQUE_LOJA12?: number | null;
  ESTOQUE_LOJA13?: number | null;
  ESTOQUE_LOJA14?: number | null;
  ESTOQUE_LOJA15?: number | null;
  ESTOQUE_LOJA16?: number | null;
  ESTOQUE_LOJA17?: number | null;
  ESTOQUE_LOJA18?: number | null;
  ESTOQUE_LOJA19?: number | null;
  ESTOQUE_LOJA20?: number | null;
  ESTOQUE_LOJA21?: number | null;
  ESTOQUE_LOJA22?: number | null;
  ESTOQUE_LOJA23?: number | null;
  ESTOQUE_LOJA24?: number | null;
  ESTOQUE_LOJA25?: number | null;
  ESTOQUE_LOJA26?: number | null;
  ESTOQUE_LOJA27?: number | null;
  ESTOQUE_LOJA28?: number | null;
  ESTOQUE_LOJA29?: number | null;
  ESTOQUE_LOJA30?: number | null;
  DEPOSITO1?: number | null;
  ESTOQUE_LOJA_BKP?: number | null;
  MINIMO_LOJA1?: number | null;
  MINIMO_LOJA2?: number | null;
  MINIMO_LOJA3?: number | null;
  MINIMO_LOJA4?: number | null;
  MINIMO_LOJA5?: number | null;
  MINIMO_LOJA6?: number | null;
  MINIMO_LOJA7?: number | null;
  MINIMO_LOJA8?: number | null;
  MINIMO_LOJA9?: number | null;
  MINIMO_LOJA10?: number | null;
  MINIMO_LOJA11?: number | null;
  MINIMO_LOJA12?: number | null;
  MINIMO_LOJA13?: number | null;
  MINIMO_LOJA14?: number | null;
  MINIMO_LOJA15?: number | null;
  MINIMO_LOJA16?: number | null;
  MINIMO_LOJA17?: number | null;
  MINIMO_LOJA18?: number | null;
  MINIMO_LOJA19?: number | null;
  MINIMO_LOJA20?: number | null;
  MINIMO_LOJA21?: number | null;
  MINIMO_LOJA22?: number | null;
  MINIMO_LOJA23?: number | null;
  MINIMO_LOJA24?: number | null;
  MINIMO_LOJA25?: number | null;
  MINIMO_LOJA26?: number | null;
  MINIMO_LOJA27?: number | null;
  MINIMO_LOJA28?: number | null;
  MINIMO_LOJA29?: number | null;
  MINIMO_LOJA30?: number | null;
  MINIMO_DEPOSITO1?: number | null;
  REPOSICAO4?: number | null;
  DT_ULT_ENTRADA?: Date | null;
  DATADOCADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  INFO_AUX?: string | null;
  COMPRAR?: number | null;
};

export type TblProdutoFisico = {
  ID_TBL_PRODUTO_FISICO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_PRODUTO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_ENTRADA?: number | null;
  ID_ENTRADA_MOVIMENTO?: number | null;
  ID_PEDIDO?: number | null;
  ID_PEDIDO_MOVIMENTO?: number | null;
  ID_CLIENTE?: number | null;
  ID_USUARIO?: number | null;
  ID_USER_EXPEDICAO?: number | null;
  ID_LOCALIZACAO?: number | null;
  ID_LOJA?: number | null;
  ID_EMPRESA?: number | null;
  ID_STATUS?: number | null;
  ESTOQUE?: number | null;
  VL_CUSTO?: number | null;
  HISTORICO?: string | null;
  PRODUTO?: string | null;
  COD_BARRAS?: string | null;
  N_SERIE?: string | null;
  NF_ENTRADA?: string | null;
  NF_SAIDA?: string | null;
  VL_VENDA?: number | null;
  ID_HISTORICO?: number | null;
  ID_STATUSRMA?: number | null;
  TAMANHO?: string | null;
  MOSTRUARIO?: string | null;
  FLAG_ABERTO_CLIENTE?: number | null;
  FLAG_DEFEITO?: number | null;
  FLAG_FORNECEDOR?: number | null;
  FLAG_OK?: number | null;
  ID_RMA?: number | null;
  AUDITORIA?: string | null;
  GARANTIA?: Date | null;
  DATA?: Date | null;
  HORA?: Date | null;
  DT_CADASTRO?: Date | null;
  DT_RETIRADA?: Date | null;
  DT_PEDIDO?: Date | null;
  MARCA?: string | null;
  DESCRICAO?: string | null;
  DT_ESTORNO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblProdutoFornecedor = {
  ID_TBL_PRODUTO_FORNECEDOR: number;
  ID_SYSTEM_CLIENTE?: number | null;
  UUID?: string | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_TBL_FORNECEDOR?: number | null;
  ID_TBL_PRODUTO?: number | null;
  ID_PESSOA?: number | null;
  PRODUTO?: string | null;
  CODIGODOPRODUTO?: string | null;
  PATH_PAGE_WEB?: string | null;
  PRAZO_ENTREGA_P_ESTOQUE?: number | null;
  PRAZO_ENTREGA_NO_CLIENTE?: number | null;
  MARCA?: string | null;
  PATH_IMAGEM_WEB?: string | null;
  GARANTIASMES?: number | null;
  GARANTIADIA?: number | null;
  CST?: string | null;
  CFOP?: string | null;
  NCM?: string | null;
  IPI?: number | null;
  ICMS?: number | null;
  INATIVO?: number | null;
  DT_ATUALIZACAO?: Date | null;
  DT_CADASTRO?: Date | null;
  ANOTACOES?: string | null;
  ID_ULT_ENTRADA?: number | null;
  DT_ULT_ENTRADA?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblProdutoImporte = {
  ID: number;
  PRODUTO?: string | null;
  VALOR?: number | null;
  SLUG?: string | null;
  FLAG_EXPORT?: number | null;
  EXPORTEDAT?: Date | null;
  CREATEDAT?: Date | null;
};

export type TblProdutoLoja = {
  ID_PRODUTO_LOJA: number;
  UUID?: string | null;
  ID_USUARIO?: number | null;
  ID_SYSTEM_ORIGEM?: number | null;
  ID_SYSTEM_DESTINO?: number | null;
  ID_PRODUTO?: number | null;
  LOJA_ORIGEM?: string | null;
  LOJA_DESTINO?: string | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
};

export type TblProdutoLojaRel = {
  ID: number;
  UUID?: string | null;
  ID_SYSTEM_ORIGEM?: number | null;
  ID_SYSTEM_DESTINO?: number | null;
  ID_PRODUTO_ORIGEM?: number | null;
  ID_PRODUTO_DESTINO?: number | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
};

export type TblProdutoMarca = {
  ID_MARCA: number;
  RECORD_ID_REV?: number | null;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  UUIDtbl_produto_fornecedor?: string | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  MARCA?: string | null;
  NOME?: string | null;
  SLUG?: string | null;
  PATH_IMAGEM?: string | null;
  INATIVO?: number | null;
  DATADOCADASTRO?: Date | null;
  ANOTACOES?: string | null;
  ID_IMAGEM?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblProdutoPreco = {
  ID_PROPRECO: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_PRODUTO?: number | null;
  OURO?: number | null;
  PRATA?: number | null;
  BRONZE?: number | null;
  VL_ATACADO1?: number | null;
  VL_ATACADO1_NEW?: number | null;
  VL_ATACADO2?: number | null;
  VL_ATACADO3?: number | null;
  VL_ATACADO4?: number | null;
  VL_ATACADO5?: number | null;
  VL_ATACADO6?: number | null;
  VL_ATACADO7?: number | null;
  VL_ATACADO8?: number | null;
  VL_ATACADO9?: number | null;
  VL_ATACADO10?: number | null;
  VL_ATACADO11?: number | null;
  VL_ATACADO12?: number | null;
  VL_ATACADO13?: number | null;
  VL_ATACADO14?: number | null;
  VL_ATACADO15?: number | null;
  VL_ATACADO16?: number | null;
  VL_ATACADO17?: number | null;
  VL_ATACADO18?: number | null;
  VL_ATACADO29?: number | null;
  VL_ATACADO19?: number | null;
  VL_ATACADO20?: number | null;
  VL_ATACADO21?: number | null;
  VL_ATACADO22?: number | null;
  VL_ATACADO23?: number | null;
  VL_ATACADO24?: number | null;
  VL_ATACADO25?: number | null;
  VL_ATACADO26?: number | null;
  VL_ATACADO27?: number | null;
  VL_ATACADO28?: number | null;
  VL_ATACADO30?: number | null;
  VL_CORPORATIVO1?: number | null;
  VL_CORPORATIVO2?: number | null;
  VL_CORPORATIVO3?: number | null;
  VL_CORPORATIVO4?: number | null;
  VL_CORPORATIVO5?: number | null;
  VL_CORPORATIVO6?: number | null;
  VL_CORPORATIVO7?: number | null;
  VL_CORPORATIVO8?: number | null;
  VL_CORPORATIVO9?: number | null;
  VL_CORPORATIVO10?: number | null;
  VL_CORPORATIVO11?: number | null;
  VL_CORPORATIVO12?: number | null;
  VL_CORPORATIVO13?: number | null;
  VL_CORPORATIVO14?: number | null;
  VL_CORPORATIVO15?: number | null;
  VL_CORPORATIVO16?: number | null;
  VL_CORPORATIVO17?: number | null;
  VL_CORPORATIVO18?: number | null;
  VL_CORPORATIVO19?: number | null;
  VL_CORPORATIVO20?: number | null;
  VL_CORPORATIVO21?: number | null;
  VL_CORPORATIVO22?: number | null;
  VL_CORPORATIVO23?: number | null;
  VL_CORPORATIVO24?: number | null;
  VL_CORPORATIVO25?: number | null;
  VL_CORPORATIVO26?: number | null;
  VL_CORPORATIVO27?: number | null;
  VL_CORPORATIVO28?: number | null;
  VL_CORPORATIVO29?: number | null;
  VL_CORPORATIVO30?: number | null;
  VL_VAREJO1?: number | null;
  VL_VAREJO2?: number | null;
  VL_VAREJO3?: number | null;
  VL_VAREJO4?: number | null;
  VL_VAREJO5?: number | null;
  VL_VAREJO6?: number | null;
  VL_VAREJO7?: number | null;
  VL_VAREJO8?: number | null;
  VL_VAREJO9?: number | null;
  VL_VAREJO10?: number | null;
  VL_VAREJO11?: number | null;
  VL_VAREJO13?: number | null;
  VL_VAREJO14?: number | null;
  VL_VAREJO15?: number | null;
  VL_VAREJO16?: number | null;
  VL_VAREJO17?: number | null;
  VL_VAREJO18?: number | null;
  VL_VAREJO19?: number | null;
  VL_VAREJO20?: number | null;
  VL_VAREJO21?: number | null;
  VL_VAREJO22?: number | null;
  VL_VAREJO23?: number | null;
  VL_VAREJO24?: number | null;
  VL_VAREJO25?: number | null;
  VL_VAREJO26?: number | null;
  VL_VAREJO27?: number | null;
  VL_VAREJO28?: number | null;
  VL_VAREJO29?: number | null;
  VL_VAREJO30?: number | null;
  TX_PRODUTO_LOJA1?: number | null;
  TX_PRODUTO_LOJA2?: number | null;
  TX_PRODUTO_LOJA3?: number | null;
  TX_PRODUTO_LOJA4?: number | null;
  TX_PRODUTO_LOJA5?: number | null;
  TX_PRODUTO_LOJA6?: number | null;
  TX_PRODUTO_LOJA7?: number | null;
  TX_PRODUTO_LOJA8?: number | null;
  TX_PRODUTO_LOJA9?: number | null;
  TX_PRODUTO_LOJA10?: number | null;
  TX_PRODUTO_LOJA11?: number | null;
  TX_PRODUTO_LOJA12?: number | null;
  TX_PRODUTO_LOJA13?: number | null;
  TX_PRODUTO_LOJA14?: number | null;
  TX_PRODUTO_LOJA15?: number | null;
  TX_PRODUTO_LOJA16?: number | null;
  TX_PRODUTO_LOJA17?: number | null;
  TX_PRODUTO_LOJA18?: number | null;
  TX_PRODUTO_LOJA19?: number | null;
  TX_PRODUTO_LOJA20?: number | null;
  TX_PRODUTO_LOJA21?: number | null;
  TX_PRODUTO_LOJA22?: number | null;
  TX_PRODUTO_LOJA23?: number | null;
  TX_PRODUTO_LOJA24?: number | null;
  TX_PRODUTO_LOJA25?: number | null;
  TX_PRODUTO_LOJA26?: number | null;
  TX_PRODUTO_LOJA27?: number | null;
  TX_PRODUTO_LOJA28?: number | null;
  TX_PRODUTO_LOJA29?: number | null;
  TX_PRODUTO_LOJA30?: number | null;
  VL_VAREJO12?: number | null;
  DECONTO1?: number | null;
  DECONTO2?: number | null;
  DECONTO3?: number | null;
  QUANTIDADE1?: number | null;
  QUANTIDADE2?: number | null;
  QUANTIDADE3?: number | null;
  TXBASEFRETE?: number | null;
  TXLUCROBRUTO_ATACADO?: number | null;
  TXLUCROBRUTO_CORPORATIVO?: number | null;
  TXLUCROBRUTO_VAREJO?: number | null;
  VL_ATACADO_ANTERIOR?: number | null;
  VL_CORPORATIVO_ANTERIOR?: number | null;
  VL_VAREJO_ANTERIOR?: number | null;
  DT_CADASTRO?: Date | null;
  TXT_DESC1?: string | null;
  TXT_DESC2?: string | null;
  TXT_DESC3?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  OURO_BKP?: number | null;
  PRATA_BKP?: number | null;
  BRONZE_BKP?: number | null;
  VL_ATACADO1_BKP?: number | null;
  VL_CORPORATIVO1_BKP?: number | null;
  VL_VAREJO1_BKP?: number | null;
  TX_VENDA_LOJA01?: number | null;
  TX_MKT_LOJA01?: number | null;
  TX_TI_LOJA01?: number | null;
};

export type TblProdutoTipo = {
  ID_TIPO: number;
  RECORD_ID_REV?: number | null;
  ID_SYSTEM_CLIENTE?: number | null;
  UUID?: string | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  TIPO?: string | null;
  SLUG?: string | null;
  INATIVO?: number | null;
  ANOTACOES?: string | null;
  FLAG_CADASTRO_PRODUTO?: number | null;
  DT_CADASTRO?: Date | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  TX_COMISSAO_VARE?: number | null;
  TX_COMISSAO_ATAC?: number | null;
};

export type TblProdutoUltEntrada = {
  ID_PRODUTO: number;
  PRODUTO?: string | null;
  ID_ULTIMO_MOVIMENTO?: number | null;
  VL_VENDA_ANTES?: number | null;
  VL_UNIT_ENT_REAL?: number | null;
  VALOR_TAXA_DOLAR?: number | null;
  VL_VENDA_DEPOIS?: number | null;
  VL_FRETE_DOLAR?: number | null;
  DIFERENCA_VALOR?: number | null;
  DIFERECA_PERC?: number | null;
  VL_VENDA_ATACADO?: number | null;
  VL_VENDA_VAREJO?: number | null;
  VL_VENDA_CORPORATIVO?: number | null;
  FLAG_UPDATE?: number | null;
};

export type TblProtocolo = {
  ID_TBL_PROTOCOLO: number;
  ID_GENERATED?: number | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_TBL_PEDIDO?: number | null;
  ID_CLIENTE?: number | null;
  ID_USUARIO?: number | null;
  ID_VENDEDOR?: number | null;
  ID_TABELA_CADASTRO?: number | null;
  ID_TABELA_PRODUTO?: number | null;
  ID_USUARIOENTREGA?: number | null;
  ID_STATUS_ENTREGA?: number | null;
  ID_SETOR?: number | null;
  TIPO?: string | null;
  CLIENTE?: string | null;
  STATUS?: string | null;
  CAIXA?: string | null;
  ID_USUARIO_RETIRADA?: number | null;
  VL_COMISSAO?: number | null;
  VL_TOTAL_PEDIDO?: number | null;
  VL_DESCONTOS?: number | null;
  VALOR?: number | null;
  ENTREGA_OK?: number | null;
  CONCLUIDO?: number | null;
  DATA?: Date | null;
  HORA?: Date | null;
  OBSERVACAO?: string | null;
  ID_STATUS_PROTOCOLO?: number | null;
  DATA_RETIRADA?: Date | null;
  CHAVE_NFE?: string | null;
  ID_STATUS_NFE?: number | null;
  FLAG_EMISSOR?: number | null;
  DATAHORA_EMISSAO?: Date | null;
  VL_PENDENTE?: number | null;
  ID_TIPO_CLIENTE?: number | null;
  VL_NFE?: number | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  DT_CADASTRO?: Date | null;
};

export type TblStatus = {
  ID_TBL_STATUS: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  STATUS: string;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
};

export type TblSystemConfig = {
  ID_SYSTEM_CONFIG: number;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_WEBSITE_START?: number | null;
  FLAG_ARREDONDAR_PRECO?: number | null;
  QT_MIN_VERSAO?: number | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
};

export type TblTaxonomy = {
  ID_TAXONOMY: number;
  RECORD_ID_REV?: number | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_SYSTEM?: number | null;
  APP_ID?: number | null;
  ID_LOJA?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  ID_TIPO?: number | null;
  UUID?: string | null;
  CONTROL?: string | null;
  PARENT_ID?: number | null;
  TAXONOMIA?: string | null;
  PATH_IMAGEM?: string | null;
  SLUG?: string | null;
  ORDEM?: number | null;
  LEVEL?: number | null;
  ID_IMAGEM?: number | null;
  QT_RECORDS?: number | null;
  INATIVO?: number | null;
  ANOTACOES?: string | null;
  META_TITLE?: string | null;
  META_DESCRIPTION?: string | null;
  UPDATEDAT?: Date | null;
  CREATEDAT?: Date | null;
};

export type TblTaxonomyRel = {
  ID_TAXONOMY: number;
  ID_RECORD: number;
  ID_SYSTEM?: number | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_TIPO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_USUARIO?: number | null;
  LEVEL?: number | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
};

export type TblTransportadora = {
  ID_TRANSPORTADORA: number;
  UUID?: string | null;
  ID_SYSTEM_CLIENTE?: number | null;
  ID_LOJA?: number | null;
  ID_USUARIO?: number | null;
  ID_DEPARTAMENTO?: number | null;
  ID_CATEGORIA?: number | null;
  ID_TIPO?: number | null;
  ID_PESSOA_TIPO?: number | null;
  ID_RESPONSAVEL?: number | null;
  ID_IMAGEM?: number | null;
  NOME?: string | null;
  FISIJURI?: string | null;
  PATH_IMAGEM?: string | null;
  FONE1?: string | null;
  FONE2?: string | null;
  WHATAPP1?: string | null;
  WHATAPP2?: string | null;
  CONTATO1?: string | null;
  CONTATO2?: string | null;
  SETOR1?: string | null;
  SETOR2?: string | null;
  EMAIL1?: string | null;
  EMAIL2?: string | null;
  RAZAO_SOCIAL?: string | null;
  CNPJ?: string | null;
  INSC_ESTADUAL?: string | null;
  INSC_MUNICIPAL?: string | null;
  NOME_FANTASIA?: string | null;
  DATA_CNPJ?: Date | null;
  NOME_RESPONSAVEL?: string | null;
  CARGO_RESPOSNAVEL?: string | null;
  ATIVIDADE_PRINCIPAL?: string | null;
  ATIVIDADES_SECUNDARIA1?: string | null;
  ATIVIDADES_SECUNDARIA2?: string | null;
  ATIVIDADES_SECUNDARIA3?: string | null;
  ATIVIDADES_SECUNDARIA4?: string | null;
  ATIVIDADES_SECUNDARIA5?: string | null;
  NATUREZA_JURIDICA?: string | null;
  OBJETIVO_MISSAO?: string | null;
  MISSAO_VISAO?: string | null;
  PRIMEIRO_NOME?: string | null;
  CARGO?: string | null;
  CPF?: string | null;
  RG?: string | null;
  GENERO?: string | null;
  SOBRENOME?: string | null;
  NOME_DO_MEIO?: string | null;
  TRATAMENTO?: string | null;
  TRABALHANAEMPRESA?: string | null;
  FORMACAOACADEMICA?: string | null;
  FORMACAOATUAL?: string | null;
  ESPECIALIZACAO?: string | null;
  INSTITUICAODEENSINO?: string | null;
  CONJUGUE?: string | null;
  DATADONASCIMENTO?: Date | null;
  CEP?: string | null;
  ENDERECO?: string | null;
  ENDERECO_NUMERO?: string | null;
  COMPLEMENTO?: string | null;
  BAIRRO?: string | null;
  CIDADE?: string | null;
  UF?: string | null;
  REGIAO_PAIS?: string | null;
  PAIS?: string | null;
  COD_MUNICIPIO?: number | null;
  COD_UF?: number | null;
  WEBSITE?: string | null;
  SKYPE?: string | null;
  FACEBOOK?: string | null;
  TWITTER?: string | null;
  FRETADOR?: number | null;
  DT_ULTIMA_COMPRA?: Date | null;
  DATADOCADASTRO?: Date | null;
  ANOTACOES?: string | null;
  DT_EXPORTE?: Date | null;
  DT_UPDATE?: Date | null;
  CREATEDAT?: Date | null;
  UPDATEDAT?: Date | null;
};

export type LogLogin = TblLogLogin;
export type LogOperation = TblLogOperation;
